### PR TITLE
Pax version process instead next cax version

### PR DESCRIPTION
**Pull request by tunnell**

### CODE REVIEW

**Comment by XeBoris** [comment]
@tunnell: Did you tested processing in Stockholm (or in general)? I applied there some changes in pax_version_process but I haven't had time to test them. I would need another look at my part of the code before merging it. I just want to avoid to mess up with reprocessing in cax because of the preparation for reprocessing in Stockholm.

**Comment by tunnell** [comment]
I'm still quite busy trying to fix a bunch of bugs that arose when adding the initial processing.  It may be a few more days before I can take a look.

**Comment by pdeperio** [comment]
sorry forgot about this when opening pull request https://github.com/XENON1T/cax/pull/18 (to master though)

**Comment by tunnell** [comment]
This is replaced by #18

**Pull request closed without merging**
