### PR TITLE
moved the file number counter inside the check of raw_size_byte

### PR DESCRIPTION
**Pull request by lucrlom**
I moved the position of nfiles because create the permission error.

### CODE REVIEW

**Comment by lucrlom** [comment]
yes, sorry

**Comment by lucrlom** [comment]
The permission problem on datamanager is still present. This means two possible solutions:
1) we found the reason why we have a different user in the raw data and we fix it
2) we delete that muon veto files from the datamanager disk

For the while I could skip the error with a try - exception, but it's no a clean solution.

**Comment by lucrlom** [comment]
Dear @XeBoris and @pdeperio,
there is another condition that raise a error that I never considered, When the process have crashed and there are not zip file inside the directory. In this case of course I receive divided by zero error. So I need to put a check for this kind of error and set in this case raw_size_byte = 0

**Comment by pdeperio** [comment]
ok, you can add to this branch.

**Comment by lucrlom** [comment]
Ciao Patrick, I found the reason of the error. There is a run with zero event but not in error. So I should just check that `build_event` exist and is not zero.

**Comment by lucrlom** [comment]
ok I fixed it

**Comment by XeBoris** [comment]
@lucrlom You can remove it, thank you.

**Pull request merged**
